CREATE TABLE IssuesBooks
(
	ID INT PRIMARY KEY IDENTITY (1,1),
	IssueID VARCHAR(MAX) NULL,
	Full_Name VARCHAR(MAX) NULL,
	Contact VARCHAR(MAX) NULL,
	Email VARCHAR(MAX) NULL,
	Book_Title VARCHAR(MAX) NULL,
	Author VARCHAR(MAX) NULL,
	Image VARCHAR(MAX) NULL,
	Return_Status VARCHAR(MAX) NULL,
	Issue_Date VARCHAR(MAX) NULL,
	Return_Date VARCHAR(MAX) NULL,
	Date_Update VARCHAR(MAX) NULL,

)

SELECT * FROM IssuesBooks