<?xml version="1.0" encoding="utf-8"?><Database Name="Library" Class="LibraryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Server=CHANGE_ME;Initial Catalog=Library;User Id=CHANGE_ME;Password=CHANGE_ME;Connect Timeout=30" SettingsObjectName="Library_Management_System_project.Properties.Settings" SettingsPropertyName="LibraryConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="date_register" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="role" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.IssuesBooks" Member="IssuesBooks">
    <Type Name="IssuesBook">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IssueID" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Full_Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Contact" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Book_Title" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Author" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Return_Status" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Issue_Date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Return_Date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Date_Update" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Insert_Date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Return_Requested_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Actual_Return_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Fines" Member="Fines">
    <Type Name="FineRecord">
      <Column Name="FineID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IssueID" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Full_Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Book_Title" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Overdue_Days" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Assessed_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Paid_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FinePayments" Member="FinePayments">
    <Type Name="FinePaymentRecord">
      <Column Name="PaymentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FineID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Bill_Code" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Reference_No" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Channel" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Created_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Completed_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BookRequests" Member="BookRequests">
    <Type Name="BookRequest">
      <Column Name="RequestID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Full_Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Contact" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="BookID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Book_Title" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Author" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Requested_Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Return_Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Decided_Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Decided_By" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Books" Member="Bookks">
    <Type Name="Bookk">
      <Column Name="BookID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Book_Title" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Author" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Published_Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Book_Status" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Date_Insert" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Date_Update" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Date_Delete" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
</Database>