#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System_project
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Library")]
	public partial class LibraryDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertIssuesBook(IssuesBook instance);
    partial void UpdateIssuesBook(IssuesBook instance);
    partial void DeleteIssuesBook(IssuesBook instance);
    partial void InsertBookk(Bookk instance);
    partial void UpdateBookk(Bookk instance);
    partial void DeleteBookk(Bookk instance);
    partial void InsertBookRequest(BookRequest instance);
    partial void UpdateBookRequest(BookRequest instance);
    partial void DeleteBookRequest(BookRequest instance);
    #endregion
		
		public LibraryDataContext() : 
				base(global::Library_Management_System_project.Properties.Settings.Default.LibraryConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LibraryDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LibraryDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LibraryDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LibraryDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<IssuesBook> IssuesBooks
		{
			get
			{
				return this.GetTable<IssuesBook>();
			}
		}
		
		public System.Data.Linq.Table<Bookk> Bookks
		{
			get
			{
				return this.GetTable<Bookk>();
			}
		}

		public System.Data.Linq.Table<BookRequest> BookRequests
		{
			get
			{
				return this.GetTable<BookRequest>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _userId;
		
		private string _email;
		
		private string _username;
		
		private string _password;
		
		private System.Nullable<System.DateTime> _date_register;

		private string _role;

    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserIdChanging(int value);
    partial void OnuserIdChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Ondate_registerChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_registerChanged();
    partial void OnroleChanging(string value);
    partial void OnroleChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(MAX)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(MAX)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(MAX)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_register", DbType="Date")]
		public System.Nullable<System.DateTime> date_register
		{
			get
			{
				return this._date_register;
			}
			set
			{
				if ((this._date_register != value))
				{
					this.Ondate_registerChanging(value);
					this.SendPropertyChanging();
					this._date_register = value;
					this.SendPropertyChanged("date_register");
					this.Ondate_registerChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}

		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IssuesBooks")]
	public partial class IssuesBook : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _IssueID;
		
		private string _Full_Name;
		
		private string _Contact;
		
		private string _Email;
		
		private string _Book_Title;
		
		private string _Author;
		
		private string _Image;
		
		private string _Return_Status;
		
		private string _Issue_Date;
		
		private string _Return_Date;
		
		private string _Date_Update;
		
		private string _Insert_Date;

		private System.Nullable<System.DateTime> _Return_Requested_Date;

    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnIssueIDChanging(string value);
    partial void OnIssueIDChanged();
    partial void OnFull_NameChanging(string value);
    partial void OnFull_NameChanged();
    partial void OnContactChanging(string value);
    partial void OnContactChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnBook_TitleChanging(string value);
    partial void OnBook_TitleChanged();
    partial void OnAuthorChanging(string value);
    partial void OnAuthorChanged();
    partial void OnImageChanging(string value);
    partial void OnImageChanged();
    partial void OnReturn_StatusChanging(string value);
    partial void OnReturn_StatusChanged();
    partial void OnIssue_DateChanging(string value);
    partial void OnIssue_DateChanged();
    partial void OnReturn_DateChanging(string value);
    partial void OnReturn_DateChanged();
    partial void OnDate_UpdateChanging(string value);
    partial void OnDate_UpdateChanged();
    partial void OnInsert_DateChanging(string value);
    partial void OnInsert_DateChanged();
    partial void OnReturn_Requested_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnReturn_Requested_DateChanged();
    #endregion

		public IssuesBook()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IssueID", DbType="VarChar(MAX)")]
		public string IssueID
		{
			get
			{
				return this._IssueID;
			}
			set
			{
				if ((this._IssueID != value))
				{
					this.OnIssueIDChanging(value);
					this.SendPropertyChanging();
					this._IssueID = value;
					this.SendPropertyChanged("IssueID");
					this.OnIssueIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Full_Name", DbType="VarChar(MAX)")]
		public string Full_Name
		{
			get
			{
				return this._Full_Name;
			}
			set
			{
				if ((this._Full_Name != value))
				{
					this.OnFull_NameChanging(value);
					this.SendPropertyChanging();
					this._Full_Name = value;
					this.SendPropertyChanged("Full_Name");
					this.OnFull_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="VarChar(MAX)")]
		public string Contact
		{
			get
			{
				return this._Contact;
			}
			set
			{
				if ((this._Contact != value))
				{
					this.OnContactChanging(value);
					this.SendPropertyChanging();
					this._Contact = value;
					this.SendPropertyChanged("Contact");
					this.OnContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(MAX)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Book_Title", DbType="VarChar(MAX)")]
		public string Book_Title
		{
			get
			{
				return this._Book_Title;
			}
			set
			{
				if ((this._Book_Title != value))
				{
					this.OnBook_TitleChanging(value);
					this.SendPropertyChanging();
					this._Book_Title = value;
					this.SendPropertyChanged("Book_Title");
					this.OnBook_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Author", DbType="VarChar(MAX)")]
		public string Author
		{
			get
			{
				return this._Author;
			}
			set
			{
				if ((this._Author != value))
				{
					this.OnAuthorChanging(value);
					this.SendPropertyChanging();
					this._Author = value;
					this.SendPropertyChanged("Author");
					this.OnAuthorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="VarChar(MAX)")]
		public string Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this.OnImageChanging(value);
					this.SendPropertyChanging();
					this._Image = value;
					this.SendPropertyChanged("Image");
					this.OnImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Return_Status", DbType="VarChar(MAX)")]
		public string Return_Status
		{
			get
			{
				return this._Return_Status;
			}
			set
			{
				if ((this._Return_Status != value))
				{
					this.OnReturn_StatusChanging(value);
					this.SendPropertyChanging();
					this._Return_Status = value;
					this.SendPropertyChanged("Return_Status");
					this.OnReturn_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Issue_Date", DbType="VarChar(MAX)")]
		public string Issue_Date
		{
			get
			{
				return this._Issue_Date;
			}
			set
			{
				if ((this._Issue_Date != value))
				{
					this.OnIssue_DateChanging(value);
					this.SendPropertyChanging();
					this._Issue_Date = value;
					this.SendPropertyChanged("Issue_Date");
					this.OnIssue_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Return_Date", DbType="VarChar(MAX)")]
		public string Return_Date
		{
			get
			{
				return this._Return_Date;
			}
			set
			{
				if ((this._Return_Date != value))
				{
					this.OnReturn_DateChanging(value);
					this.SendPropertyChanging();
					this._Return_Date = value;
					this.SendPropertyChanged("Return_Date");
					this.OnReturn_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_Update", DbType="VarChar(MAX)")]
		public string Date_Update
		{
			get
			{
				return this._Date_Update;
			}
			set
			{
				if ((this._Date_Update != value))
				{
					this.OnDate_UpdateChanging(value);
					this.SendPropertyChanging();
					this._Date_Update = value;
					this.SendPropertyChanged("Date_Update");
					this.OnDate_UpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Insert_Date", DbType="VarChar(MAX)")]
		public string Insert_Date
		{
			get
			{
				return this._Insert_Date;
			}
			set
			{
				if ((this._Insert_Date != value))
				{
					this.OnInsert_DateChanging(value);
					this.SendPropertyChanging();
					this._Insert_Date = value;
					this.SendPropertyChanged("Insert_Date");
					this.OnInsert_DateChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Return_Requested_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Return_Requested_Date
		{
			get
			{
				return this._Return_Requested_Date;
			}
			set
			{
				if ((this._Return_Requested_Date != value))
				{
					this.OnReturn_Requested_DateChanging(value);
					this.SendPropertyChanging();
					this._Return_Requested_Date = value;
					this.SendPropertyChanged("Return_Requested_Date");
					this.OnReturn_Requested_DateChanged();
				}
			}
		}

		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BookRequests")]
	public partial class BookRequest : INotifyPropertyChanging, INotifyPropertyChanged
	{

		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

		private int _RequestID;

		private string _Email;

		private string _Full_Name;

		private string _Contact;

		private int _BookID;

		private string _Book_Title;

		private string _Author;

		private System.Nullable<System.DateTime> _Requested_Date;

		private System.Nullable<System.DateTime> _Return_Date;

		private string _Status;

		private System.Nullable<System.DateTime> _Decided_Date;

		private string _Decided_By;

    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRequestIDChanging(int value);
    partial void OnRequestIDChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnFull_NameChanging(string value);
    partial void OnFull_NameChanged();
    partial void OnContactChanging(string value);
    partial void OnContactChanged();
    partial void OnBookIDChanging(int value);
    partial void OnBookIDChanged();
    partial void OnBook_TitleChanging(string value);
    partial void OnBook_TitleChanged();
    partial void OnAuthorChanging(string value);
    partial void OnAuthorChanged();
    partial void OnRequested_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnRequested_DateChanged();
    partial void OnReturn_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnReturn_DateChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnDecided_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnDecided_DateChanged();
    partial void OnDecided_ByChanging(string value);
    partial void OnDecided_ByChanged();
    #endregion

		public BookRequest()
		{
			OnCreated();
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RequestID
		{
			get
			{
				return this._RequestID;
			}
			set
			{
				if ((this._RequestID != value))
				{
					this.OnRequestIDChanging(value);
					this.SendPropertyChanging();
					this._RequestID = value;
					this.SendPropertyChanged("RequestID");
					this.OnRequestIDChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(MAX)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Full_Name", DbType="VarChar(MAX)")]
		public string Full_Name
		{
			get
			{
				return this._Full_Name;
			}
			set
			{
				if ((this._Full_Name != value))
				{
					this.OnFull_NameChanging(value);
					this.SendPropertyChanging();
					this._Full_Name = value;
					this.SendPropertyChanged("Full_Name");
					this.OnFull_NameChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="VarChar(MAX)")]
		public string Contact
		{
			get
			{
				return this._Contact;
			}
			set
			{
				if ((this._Contact != value))
				{
					this.OnContactChanging(value);
					this.SendPropertyChanging();
					this._Contact = value;
					this.SendPropertyChanged("Contact");
					this.OnContactChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookID", DbType="Int NOT NULL")]
		public int BookID
		{
			get
			{
				return this._BookID;
			}
			set
			{
				if ((this._BookID != value))
				{
					this.OnBookIDChanging(value);
					this.SendPropertyChanging();
					this._BookID = value;
					this.SendPropertyChanged("BookID");
					this.OnBookIDChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Book_Title", DbType="VarChar(MAX)")]
		public string Book_Title
		{
			get
			{
				return this._Book_Title;
			}
			set
			{
				if ((this._Book_Title != value))
				{
					this.OnBook_TitleChanging(value);
					this.SendPropertyChanging();
					this._Book_Title = value;
					this.SendPropertyChanged("Book_Title");
					this.OnBook_TitleChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Author", DbType="VarChar(MAX)")]
		public string Author
		{
			get
			{
				return this._Author;
			}
			set
			{
				if ((this._Author != value))
				{
					this.OnAuthorChanging(value);
					this.SendPropertyChanging();
					this._Author = value;
					this.SendPropertyChanged("Author");
					this.OnAuthorChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Requested_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Requested_Date
		{
			get
			{
				return this._Requested_Date;
			}
			set
			{
				if ((this._Requested_Date != value))
				{
					this.OnRequested_DateChanging(value);
					this.SendPropertyChanging();
					this._Requested_Date = value;
					this.SendPropertyChanged("Requested_Date");
					this.OnRequested_DateChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Return_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Return_Date
		{
			get
			{
				return this._Return_Date;
			}
			set
			{
				if ((this._Return_Date != value))
				{
					this.OnReturn_DateChanging(value);
					this.SendPropertyChanging();
					this._Return_Date = value;
					this.SendPropertyChanged("Return_Date");
					this.OnReturn_DateChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Decided_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Decided_Date
		{
			get
			{
				return this._Decided_Date;
			}
			set
			{
				if ((this._Decided_Date != value))
				{
					this.OnDecided_DateChanging(value);
					this.SendPropertyChanging();
					this._Decided_Date = value;
					this.SendPropertyChanged("Decided_Date");
					this.OnDecided_DateChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Decided_By", DbType="VarChar(MAX)")]
		public string Decided_By
		{
			get
			{
				return this._Decided_By;
			}
			set
			{
				if ((this._Decided_By != value))
				{
					this.OnDecided_ByChanging(value);
					this.SendPropertyChanging();
					this._Decided_By = value;
					this.SendPropertyChanged("Decided_By");
					this.OnDecided_ByChanged();
				}
			}
		}

		public event PropertyChangingEventHandler PropertyChanging;

		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}

		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Books")]
	public partial class Bookk : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BookID;
		
		private string _Book_Title;
		
		private string _Author;
		
		private System.Nullable<System.DateTime> _Published_Date;
		
		private string _Book_Status;
		
		private System.Nullable<System.DateTime> _Date_Insert;
		
		private System.Nullable<System.DateTime> _Date_Update;
		
		private string _Image;
		
		private System.Nullable<System.DateTime> _Date_Delete;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBookIDChanging(int value);
    partial void OnBookIDChanged();
    partial void OnBook_TitleChanging(string value);
    partial void OnBook_TitleChanged();
    partial void OnAuthorChanging(string value);
    partial void OnAuthorChanged();
    partial void OnPublished_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnPublished_DateChanged();
    partial void OnBook_StatusChanging(string value);
    partial void OnBook_StatusChanged();
    partial void OnDate_InsertChanging(System.Nullable<System.DateTime> value);
    partial void OnDate_InsertChanged();
    partial void OnDate_UpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnDate_UpdateChanged();
    partial void OnImageChanging(string value);
    partial void OnImageChanged();
    partial void OnDate_DeleteChanging(System.Nullable<System.DateTime> value);
    partial void OnDate_DeleteChanged();
    #endregion
		
		public Bookk()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int BookID
		{
			get
			{
				return this._BookID;
			}
			set
			{
				if ((this._BookID != value))
				{
					this.OnBookIDChanging(value);
					this.SendPropertyChanging();
					this._BookID = value;
					this.SendPropertyChanged("BookID");
					this.OnBookIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Book_Title", DbType="VarChar(MAX)")]
		public string Book_Title
		{
			get
			{
				return this._Book_Title;
			}
			set
			{
				if ((this._Book_Title != value))
				{
					this.OnBook_TitleChanging(value);
					this.SendPropertyChanging();
					this._Book_Title = value;
					this.SendPropertyChanged("Book_Title");
					this.OnBook_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Author", DbType="VarChar(MAX)")]
		public string Author
		{
			get
			{
				return this._Author;
			}
			set
			{
				if ((this._Author != value))
				{
					this.OnAuthorChanging(value);
					this.SendPropertyChanging();
					this._Author = value;
					this.SendPropertyChanged("Author");
					this.OnAuthorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Published_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Published_Date
		{
			get
			{
				return this._Published_Date;
			}
			set
			{
				if ((this._Published_Date != value))
				{
					this.OnPublished_DateChanging(value);
					this.SendPropertyChanging();
					this._Published_Date = value;
					this.SendPropertyChanged("Published_Date");
					this.OnPublished_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Book_Status", DbType="VarChar(MAX)")]
		public string Book_Status
		{
			get
			{
				return this._Book_Status;
			}
			set
			{
				if ((this._Book_Status != value))
				{
					this.OnBook_StatusChanging(value);
					this.SendPropertyChanging();
					this._Book_Status = value;
					this.SendPropertyChanged("Book_Status");
					this.OnBook_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_Insert", DbType="Date")]
		public System.Nullable<System.DateTime> Date_Insert
		{
			get
			{
				return this._Date_Insert;
			}
			set
			{
				if ((this._Date_Insert != value))
				{
					this.OnDate_InsertChanging(value);
					this.SendPropertyChanging();
					this._Date_Insert = value;
					this.SendPropertyChanged("Date_Insert");
					this.OnDate_InsertChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_Update", DbType="Date")]
		public System.Nullable<System.DateTime> Date_Update
		{
			get
			{
				return this._Date_Update;
			}
			set
			{
				if ((this._Date_Update != value))
				{
					this.OnDate_UpdateChanging(value);
					this.SendPropertyChanging();
					this._Date_Update = value;
					this.SendPropertyChanged("Date_Update");
					this.OnDate_UpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="VarChar(MAX)")]
		public string Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this.OnImageChanging(value);
					this.SendPropertyChanging();
					this._Image = value;
					this.SendPropertyChanged("Image");
					this.OnImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_Delete", DbType="Date")]
		public System.Nullable<System.DateTime> Date_Delete
		{
			get
			{
				return this._Date_Delete;
			}
			set
			{
				if ((this._Date_Delete != value))
				{
					this.OnDate_DeleteChanging(value);
					this.SendPropertyChanging();
					this._Date_Delete = value;
					this.SendPropertyChanged("Date_Delete");
					this.OnDate_DeleteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
